### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by saggy2012** [fictitious/test-systemjs-angular-gulp#2]
Hi ,
  I have implemented budling by following all steps given here. but i m getting below error 
only difference is all my component call happen through MVC controller. and we don have .html files for components. i see bundled files getting renderd in fiddler.
can somebody please help me on this ?

Unhandled Promise rejection: TypeError: Cannot read property 'get' of undefined
	    at http://localhost:56726/production/app.bundle.js:1:11141
	    at ZoneDelegate.invoke (http://localhost:56726/node_modules/zone.js/dist/zone.js:232:26)
	Error loading http://localhost:56726/dist/configs/systemjs.config.js ; Zone: <root> ; Task: Promise.then ; Value: Error: TypeError: Cannot read property 'get' of undefined
	    at http://localhost:56726/production/app.bundle.js:1:11141
	    at ZoneDelegate.invoke (http://localhost:56726/node_modules/zone.js/dist/zone.js:232:26)
	Error loading http://localhost:56726/dist/configs/systemjs.config.js null

**Comment by mkariti** [comment]
Hi @saggy2012 ,
Any luck?
Im facing the same issue.....
Regards

**Comment by mkariti** [comment]
Hi @saggy2012 ,
Have a look [here](https://github.com/systemjs/systemjs/issues/1613).
For me it was SystemJsBuilder compatibility issues.

**Comment by saggy2012** [comment]
Yes.. the issue was because of systemjs.config was getting included in
bundled file.. once i manaully deleted tht content and it worked.. make
sure that systemjs.config doesnt get included in ..
